frontend:
  image: frontend:latest
  build:
    context: ./frontend/
    dockerfile: Dockerfile.dev
  working_dir: /app
  stdin_open: true
  ports:
    - "3000:3000"
  volumes:
    - ./frontend/:/app
    - frontend_node_modules:/app/node_modules
  environment:
    - NODE_ENV=development
  command: bash -c "npm install && npm start"

volumes:
  frontend_node_modules:
