frontend:
  image: frontend:latest
  build:
    context: ./frontend/
    dockerfile: Dockerfile.dev
  working_dir: /app
  stdin_open: true
  ports:
    - "3000:3000"
  volumes:
    - ./frontend/:/app
    - frontend_node_modules:/app/node_modules
  environment:
    - REACT_APP_API_HOST=${API_HOST:-localhost}
    - REACT_APP_API_PORT=${API_PORT:-5000}
    - REACT_APP_DEVELOP=true
  command: bash -c "npm install && npm start"

volumes:
  frontend_node_modules:
