version: "1.0"
name: Debug
metadata:
  type: extractive
arguments:
  fail:
    type: bool
    default: true
  error:
    type: categorical
    categories:
      - ValueError
      - Exception
      - AttributeError
    default: ValueError
  error_message:
    type: str
    default: test error
  time:
    type: int
    default: 0
    min: -1
    max: 1000
  extra_message:
    type: float
    default: 0
    min: -500
    max: 500
  summary:
    type: str
    default: test summary
  high_load:
    type: bool
    default: true
