env:
  browser: true
  node: true
extends:
  - airbnb
  - prettier
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
parser: "babel-eslint"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - prettier
  - react
  - react-hooks
  - simple-import-sort
  - import
  - promise
rules:
  react/function-component-definition: 0
  react/react-in-jsx-scope: 0
  react/jsx-filename-extension: 0
  react/no-array-index-key: 0
  react/prop-types: 0
  import/prefer-default-export: 0
  react/button-has-type: 0
  no-underscore-dangle: 0
  react/jsx-props-no-spreading: 0
  no-plusplus: 0
  react/display-name: 0
  jsx-a11y/anchor-has-content: 0
  jsx-a11y/control-has-associated-label: 0
  jsx-a11y/label-has-associated-control: 0
  jsx-a11y/no-autofocus: 0
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/no-static-element-interactions: 0
  no-constant-condition: 0
  import/no-extraneous-dependencies: 0
  no-restricted-syntax: 0
  no-unused-vars: "warn"
