docker_username: ds40bamo
deploy:
  nodeport: 30900

metrics:
  - ./metrics/bert
  - ./metrics/bleu
  - ./metrics/bleurt
  - ./metrics/cider
  - ./metrics/greedy_matching
  - ./metrics/meteor
  - ./metrics/moverscore
  - ./metrics/rouge
  - ./metrics/sentence_transformers
  - ./metrics/cosine_similarity

summarizers:
  - ./summarizers/bertsum
  - ./summarizers/textrank
  - ./summarizers/newspaper3k
  - ./summarizers/pytextrank
  - source: ./summarizers/neuralsum
    config:
      name: t5
      readable: T5
      model: T5
  - source: ./summarizers/neuralsum
    config:
      name: bartcnn
      readable: BART-CNN
      model: BART-CNN
  - source: ./summarizers/neuralsum
    config:
      name: bartxsum
      readable: BART-XSum
      model: BART-XSum
  - source: ./summarizers/neuralsum
    config:
      name: pegasuscnn
      readable: Pegasus-CNN
      model: Pegasus-CNN
  - source: ./summarizers/neuralsum
    config:
      name: pegasusxsum
      readable: Pegasus-XSum
      model: Pegasus-XSum
  - source: ./summarizers/neuralsum
    config:
      name: longformer2roberta
      readable: Longformer2Roberta
      model: Longformer2Roberta
