docker_username: ds40bamo
deploy:
  host: tldr.demo.webis.de

metrics:
  - ./metrics/bert
  - ./metrics/bleu
  - ./metrics/bleurt
  - ./metrics/cider
  - ./metrics/greedy_matching
  - ./metrics/meteor
  - ./metrics/moverscore
  - ./metrics/rouge
  - ./metrics/sentence_transformers
  - ./metrics/cosine_similarity

summarizers:
  - ./summarizers/bertsum
  - ./summarizers/textrank
  - ./summarizers/newspaper3k
  - ./summarizers/longformer2roberta
  - source: ./summarizers/neuralsum
    environment:
      model: T5
  - source: ./summarizers/neuralsum
    environment:
      model: BART-CNN
  - source: ./summarizers/neuralsum
    environment:
      model: BART-XSum
  - source: ./summarizers/neuralsum
    environment:
      model: Pegasus-CNN
  - source: ./summarizers/neuralsum
    environment:
      model: Pegasus-XSum
