version: "3"
services:
  backend:
    image: summarizer-backend:latest
    build: backend/
    working_dir: /app
    volumes:
      - ./backend/:/app
      - root:/root
    environment:
      - INSTALL_ALWAYS
      - MONGODB_HOST=mongodb://mongo/app
      - GUNICORN_CMD_ARGS="-cgunicorn.conf.py"
    command: bash -c "python setup.py && gunicorn wsgi:app"

  frontend:
    image: summarizer-frontend:latest
    build: frontend/
    working_dir: /app

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  mongo:
    image: mongo:latest
    volumes:
      - mongodata:/data/db

volumes:
  root:
  mongodata:
