version: '3'

services:
  api:
    image: api:latest
    build: docker/backend/api
    working_dir: /app
    ports:
      - 5000:5000
    volumes:
      - ./backend/api/:/app
      - api_root:/root
    environment:
      - MONGODB_HOST=mongodb://mongo/app
      - BERT_URL=http://bert:5000
      - BLEURT_URL=http://bleurt:5000
      - GREEDY_MATCHING_URL=http://greedy_matching:5000
      - METEOR_URL=http://meteor:5000
      - MOVER_SCORE_URL=http://moverscore:5000
      - SIMPLE_METRICS_URL=http://simple_metrics:5000
      - BERTSUM_URL=http://bertsum:5000
      - SIMPLE_SUMMARIZERS_URL=http://simple_summarizers:5000
    command: bash -c "pipenv sync && pipenv run python wsgi.py"

  simple_metrics:
    image: simple:latest
    build: docker/backend/slim
    working_dir: /app
    volumes:
      - ./backend/metrics/simple/:/app
      - simple_metrics_root:/root
    command: bash -c "pipenv sync && pipenv run python wsgi.py"

  frontend:
    image: frontend:latest
    build: docker/frontend
    working_dir: /app
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/app
      - node_modules:/app/node_modules
    environment:
      - REACT_APP_API_HOST=${API_HOST:-localhost}
      - REACT_APP_API_PORT=${API_PORT:-5000}
      - REACT_APP_DEVELOP=true
    command: bash -c "npm install && npm start"

  mongo:
    image: mongo:latest
    volumes:
      - mongodata:/data/db

volumes:
  api_root:
  bert_root:
  bleurt_root:
  greedy_matching_root:
  moverscore_root:
  simple_metrics_root:
  bertsum_root:
  simple_summarizers_root:
  node_modules:
  mongodata:
