version: "3"
services:
  backend:
    image: backend:latest
    build: docker/backend
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - ./backend/:/app
      - cache:/root/.cache
      - nltk_data:/root/nltk_data
      - virtualenvs:/root/.local/share/virtualenvs
    environment:
      - INSTALL_ALWAYS
      - MONGODB_HOST=mongodb://mongo/app
    command: bash -c "bash /utils/wait-for-it.sh -t 0 mongo:27017 && bash boot.sh"

  frontend:
    image: frontend:latest
    build: docker/frontend
    working_dir: /app
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app
      - node_modules:/app/node_modules
    environment:
      - REACT_APP_API_HOST=${API_HOST:-localhost}
      - REACT_APP_API_PORT=${API_PORT:-5000}
      - REACT_APP_DEVELOP=true
    command: bash -c "npm install && npm start"

  mongo:
    image: mongo:latest
    volumes:
      - mongodata:/data/db

volumes:
  cache:
  nltk_data:
  node_modules:
  virtualenvs:
  mongodata:
