docker_username: ds40bamo
deploy:
  host: tldr.demo.webis.de

metrics:
  - ./metrics/bartscore
  - ./metrics/bert
  - ./metrics/bleu
  - ./metrics/bleurt
  - ./metrics/cider
  - ./metrics/cosine_similarity
  - ./metrics/greedy_matching
  - ./metrics/meteor
  - ./metrics/moverscore
  - ./metrics/rouge
  - ./metrics/sentence_transformers

summarizers:
  - ./summarizers/argpagerank
  - ./summarizers/bertsum
  - ./summarizers/biasedtextrank
  - ./summarizers/conclugen
  - ./summarizers/gsum
  - ./summarizers/lobart
  - ./summarizers/longformer2roberta
  - ./summarizers/newspaper3k
  - ./summarizers/pmisum
  - ./summarizers/positionrank
  - ./summarizers/textrank
  - ./summarizers/topicrank
  - ./summarizers/extractive
  - source: ./summarizers/cliffsum
    environment:
      model: MaskEnt
  - source: ./summarizers/cliffsum
    environment:
      model: MaskRel
  - source: ./summarizers/cliffsum
    environment:
      model: RegenEnt
  - source: ./summarizers/cliffsum
    environment:
      model: RegenRel
  - source: ./summarizers/cliffsum
    environment:
      model: SwapEnt
  - source: ./summarizers/cliffsum
    environment:
      model: SysLowCon
  - source: ./summarizers/coopsum
    environment:
      model: COOP-Amazon
  - source: ./summarizers/coopsum
    environment:
      model: COOP-Yelp
  - source: ./summarizers/neuralsum
    environment:
      model: T5
  - source: ./summarizers/neuralsum
    environment:
      model: BART-CNN
  - source: ./summarizers/neuralsum
    environment:
      model: BART-XSum
  - source: ./summarizers/neuralsum
    environment:
      model: Pegasus-CNN
  - source: ./summarizers/neuralsum
    environment:
      model: Pegasus-XSum
