apiVersion: v1
kind: ConfigMap
metadata:
  name: summary-workbench-plugins
data:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summary-workbench-api
  labels:
    app: summary-workbench
    tier: api
spec:
  selector:
    matchLabels:
      app: summary-workbench
      tier: api
  template:
    metadata:
      labels:
        app: summary-workbench
        tier: api
    spec:
      volumes:
        - name: plugin-config
          configMap:
            name: summary-workbench-plugins
      containers:
        - name: api
          image:
          imagePullPolicy: Always
          env:
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: token-secrets
                  key: access-token-secret
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: token-secrets
                  key: refresh-token-secret
            - name: NODE_ENV
              value: "production"
            - name: MONGODB_HOST
              value: "mongodb://summary-workbench-mongodb/app"
            - name: GROBID_HOST
              value: "http://summary-workbench-grobid:8070"
          ports:
            - name: api-port
              containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: plugin-config
              subPath: plugin_config.json
              mountPath: /plugin_config/plugin_config.json
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health
              port: api-port
            periodSeconds: 60
            timeoutSeconds: 60
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: summary-workbench-api
spec:
  selector:
    app: summary-workbench
    tier: api
  ports:
    - port: 5000
      targetPort: api-port
