apiVersion: apps/v1
kind: Deployment
metadata:
  name: summary-workbench-frontend
  labels:
    app: summary-workbench
    tier: frontend
spec:
  selector:
    matchLabels:
      app: summary-workbench
      tier: frontend
  template:
    metadata:
      labels:
        app: summary-workbench
        tier: frontend
    spec:
      containers:
        - name: frontend
          image:
          imagePullPolicy: Always
          env: []
          ports:
            - name: frontend-port
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: frontend-port
            periodSeconds: 15
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: summary-workbench-frontend
spec:
  selector:
    app: summary-workbench
    tier: frontend
  ports:
    - port: 80
      targetPort: frontend-port
