apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tldr-ingress
  annotations:
    nginx.ingress.kubernetes.io/client-max-body-size: '512m'
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '3000'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3000'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3000'
spec:
  rules:
    - host:
      http:
        paths:
          - path: /
            backend:
              serviceName: tldr
              servicePort: 80
