apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tldr
spec:
  rules:
    - host:
      http:
        paths:
          - path: /
            backend:
              serviceName: tldr
              servicePort: 80
