apiVersion: v1
kind: ConfigMap
metadata:
  name: summary-workbench-proxy
data:
  nginx.conf: |-
    worker_processes 1;

    events {
      worker_connections 1024;
    }

    http {
      access_log off;
      server {
        listen 80;

        location / {
          proxy_pass http://summary-workbench-frontend:80;
        }

        location /api {
          client_max_body_size 30M;
          proxy_connect_timeout 3000;
          proxy_send_timeout 3000;
          proxy_read_timeout 3000;
          send_timeout 3000;

          proxy_pass http://summary-workbench-api:5000;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summary-workbench-proxy
  labels:
    app: summary-workbench
    tier: proxy
spec:
  selector:
    matchLabels:
      app: summary-workbench
      tier: proxy
  template:
    metadata:
      labels:
        app: summary-workbench
        tier: proxy
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: summary-workbench-proxy
      containers:
        - name: proxy
          image: nginx:alpine
          ports:
            - name: sw-port
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              subPath: nginx.conf
              mountPath: "/etc/nginx/nginx.conf"
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: sw-port
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: summary-workbench
spec:
  selector:
    app: summary-workbench
    tier: proxy
  ports:
    - port: 80
      targetPort: sw-port
