apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer-api
  labels:
    app: summarizer
    tier: api
spec:
  selector:
    matchLabels:
      app: summarizer
      tier: api
  template:
    metadata:
      labels:
        app: summarizer
        tier: api
    spec:
      containers:
        - name: api
          image:
          imagePullPolicy: Always
          env:
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: token-secrets
                  key: access-token-secret
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: token-secrets
                  key: refresh-token-secret
            - name: NODE_ENV
              value: "production"
            - name: MONGODB_HOST
              value: "mongodb://summarizer-mongodb/app"
          ports:
            - name: api-port
              containerPort: 5000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: api-port
            periodSeconds: 60
            timeoutSeconds: 60
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: summarizer-api
spec:
  selector:
    app: summarizer
    tier: api
  ports:
    - port: 5000
      targetPort: api-port
