version: "1.0"
name: moverscore
readable: MoverScore
type: semantic
model: MoverScoreV2
homepage: https://arxiv.org/pdf/1909.02622.pdf
sourcecode: https://github.com/AIPHES/emnlp19-moverscore
devimage: default
deployimage: default
