version: "1.0"
name: MoverScore
devimage: default
deployimage: default
metadata:
  type: semantic
  model: MoverScoreV1
  homepage: https://arxiv.org/pdf/1909.02622.pdf
  sourcecode: https://github.com/AIPHES/emnlp19-moverscore
