version: "1.0"
name: "{model}"
devimage: slim
deployimage: slim
metadata:
  type: abstractive
  homepage: "https://aclanthology.org/2021.findings-emnlp.328/"
  sourcecode: "https://github.com/megagonlabs/coop"
