version: "1.0"
name: Newspaper3k
devimage: slim
deployimage: slim
metadata:
  type: extractive
  homepage: https://newspaper.readthedocs.io/en/latest/
  sourcecode: https://github.com/codelucas/newspaper/
