version: "1.0"
name: newspaper3k
readable: Newspaper3k
type: extractive
sourcecode: https://github.com/codelucas/newspaper/
homepage: https://newspaper.readthedocs.io/en/latest/
devimage: slim
deployimage: slim
