kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: comparefile-mongodb-data
  labels:
    app: comparefile
    tier: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-rbd
