version: "1.0"
name: TextRank
devimage: slim
deployimage: slim
metadata:
  type: extractive
  homepage: https://www.aclweb.org/anthology/W04-3252/
  sourcecode: https://github.com/DerwenAI/pytextrank
