kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: summary-workbench-mongodb-data
  labels:
    app: summary-workbench
    tier: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-rbd
