kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tldr-mongodb-data
  labels:
    app: tldr
    tier: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-rbd
