apiVersion: v1
kind: ConfigMap
metadata:
  name: summarizer-plugins
data: |-
  {
    "METRICS": {
      "bleu": {
        "homepage": "https://www.aclweb.org/anthology/P02-1040.pdf",
        "sourcecode": "https://github.com/mjpost/sacreBLEU",
        "version": "1.0",
        "readable": "BLEU",
        "model": null,
        "type": "lexical"
      }
    },
    "SUMMARIZERS": {}
  }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer-api
  labels:
    app: summarizer
    tier: api
spec:
  selector:
    matchLabels:
      app: summarizer
      tier: api
  template:
    metadata:
      labels:
        app: summarizer
        tier: api
    spec:
      containers:
        - name: api
          image: docker.io/ds40bamo/tldr-api:1.3.2
          imagePullPolicy: Always
          env:
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: token-secrets
                  key: access-token-secret
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: token-secrets
                  key: refresh-token-secret
            - name: NODE_ENV
              value: production
            - name: MONGODB_HOST
              value: mongodb://summarizer-mongodb/app
            - name: BLEU_METRIC_URL
              value: http://metric_bleu:5000
          ports:
            - name: api-port
              containerPort: 5000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: api-port
            periodSeconds: 60
            timeoutSeconds: 60
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: summarizer-api
spec:
  selector:
    app: summarizer
    tier: api
  ports:
    - port: 5000
      targetPort: api-port
