apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer-bert
  labels:
    app: summarizer
    tier: bert
spec:
  selector:
    matchLabels:
      app: summarizer
      tier: bert
  template:
    metadata:
      labels:
        app: summarizer
        tier: bert
    spec:
      containers:
        - name: bert
          image: docker.io/ds40bamo/bert:1.0
          imagePullPolicy: Always
          command: ["bash", "-c", "gunicorn wsgi:app"]
          env:
            - name: GUNICORN_CMD_ARGS
              value: "-cgunicorn.conf.py"
          ports:
            - name: bert-port
              containerPort: 5000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: bert-port
            periodSeconds: 60
            timeoutSeconds: 60
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: summarizer-bert
spec:
  selector:
    app: summarizer
    tier: bert
  ports:
    - port: 5000
      targetPort: bert-port
