apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer-frontend
  labels:
    app: summarizer
    tier: frontend
spec:
  selector:
    matchLabels:
      app: summarizer
      tier: frontend
  template:
    metadata:
      labels:
        app: summarizer
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/ds40bamo/summarizer-frontend:1.2.3
          imagePullPolicy: Always
          ports:
            - name: frontend-port
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: frontend-port
            periodSeconds: 15
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: summarizer-frontend
spec:
  selector:
    app: summarizer
    tier: frontend
  ports:
    - port: 80
      targetPort: frontend-port
