env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - prettier
  - eslint:recommended
plugins:
  - prettier
  - simple-import-sort
  - import
  - promise
parserOptions:
  ecmaVersion: latest
rules:
  no-console: 0
  max-classes-per-file: 0
  no-await-in-loop: 0
  no-restricted-syntax: 0
